version: '2'
services:
  db:
    image: mariadb
    environment:
       - MYSQL_ROOT_PASSWORD=admin
       - MYSQL_USER=moodle
       - MYSQL_PASSWORD=moodle
       - MYSQL_DATABASE=moodle
  moodle:
    build: .
    expose:
      - "80"
#    ports:
#      - 8090:80
    links:
      - db
    volumes:
      - ./miquiz-plugin/:/var/www/htdocs/mod/miquiz/
    environment:
      - MOODLE_URL=https://$SERVER
      - SERVER_NAME=$SERVER
      - VIRTUAL_HOST=$SERVER
      - CERT_NAME=mi-quiz
      - HTTPS_METHOD=noredirect
