services:
  db:
    image: mariadb:10.4
    environment:
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_USER=moodle
      - MARIADB_PASSWORD=moodle
      - MARIADB_DATABASE=moodle
    volumes:
      - ./startup_db.sql:/docker-entrypoint-initdb.d/dump.sql
  moodle:
    build:
      context: .
      args:
        - MOODLE_URL=$SERVER
    ports:
      - ${PORT}:80
    links:
      - db
    volumes:
      - ./:/var/www/html/mod/miquiz/
